<#
.SYNOPSIS
  Builds FRENCH_REVIEW.md from the shipped Keyed and DefInjected XML, for TRANSLATIONS.md's
  "Systematic French review by Virginie" (2026-09-30).
.DESCRIPTION
  Reads every Mod/Languages/French/{Keyed,DefInjected}/**/*.xml key. For each key, resolves the
  English text: a matching Mod/Languages/English file+key if one exists, otherwise the native
  English value read directly from the shipped Def in Mod/Defs (label/description/stage/tool
  fields resolved by dotted path against the Def's own XML, mirroring how the game itself falls
  back). This is why the file is built by a script, not by hand: the fallback path differs key by
  key, and a hand-copy cannot be trusted not to drift.

  Original (source-language) text: the ported original, "Paddleboard", has no repository and its
  own English source is what this mod's Defs and English Keyed file already carry (ATTRIBUTION.md:
  "the original has no repository"; nothing here names a non-English source language). So Original
  equals English throughout, said once here rather than on every row.
#>
param(
    [string]$Root = (Split-Path $PSScriptRoot -Parent),
    [string]$OutFile = (Join-Path (Split-Path $PSScriptRoot -Parent) 'FRENCH_REVIEW.md')
)

function Get-Entries($path) {
    $entries = [ordered]@{}
    if (-not (Test-Path $path)) { return $entries }
    $xml = [xml](Get-Content $path -Raw -Encoding UTF8)
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $entries[$node.Name] = $node.InnerText
    }
    return $entries
}

function Resolve-DefField($defsRoot, [string]$key) {
    # key looks like "DefName.field" or "DefName.degreeDatas.N.field"
    $parts = $key -split '\.'
    $defName = $parts[0]
    $rest = $parts[1..($parts.Length - 1)]
    if (-not $script:defCache.ContainsKey($defName)) {
        $found = $null
        foreach ($f in $script:defFiles) {
            $x = [xml](Get-Content $f -Raw -Encoding UTF8)
            $node = $x.SelectSingleNode("//*[defName='$defName']")
            if ($node) { $found = $node; break }
        }
        $script:defCache[$defName] = $found
    }
    $node = $script:defCache[$defName]
    if (-not $node) { return $null }
    $cur = $node
    foreach ($p in $rest) {
        if ($cur -eq $null) { return $null }
        if ($p -match '^\d+$') {
            $children = @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })
            $idx = [int]$p
            if ($idx -ge $children.Count) { return $null }
            $cur = $children[$idx]
        }
        elseif ($p -eq 'degreeDatas' -and $cur.degreeDatas) {
            $cur = $cur.degreeDatas
        }
        else {
            # TraitDegreeData entries are addressed by label, not index (05-captures.feature note):
            # try a child whose own <label> equals the next path segment, else fall through to a plain child.
            $byLabel = $null
            if ($cur.ChildNodes) {
                foreach ($child in @($cur.ChildNodes | Where-Object { $_.NodeType -eq 'Element' })) {
                    if ($child.label -eq $p) { $byLabel = $child; break }
                }
            }
            if ($byLabel) { $cur = $byLabel } else { $cur = $cur.$p }
        }
    }
    if ($cur -is [System.Xml.XmlElement]) { return $cur.InnerText }
    if ($cur) { return [string]$cur }
    return $null
}

$frenchRoot = Join-Path $Root 'Mod/Languages/French'
$englishRoot = Join-Path $Root 'Mod/Languages/English'
$defsRoot = Join-Path $Root 'Mod/Defs'
$script:defFiles = Get-ChildItem $defsRoot -Recurse -Filter *.xml | ForEach-Object { $_.FullName }
$script:defCache = @{}

$frenchFiles = Get-ChildItem $frenchRoot -Recurse -Filter *.xml | Sort-Object FullName
$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine("# French review")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated by ``_tools/Generate-FrenchReview.ps1`` for TRANSLATIONS.md's systematic French review.")
[void]$out.AppendLine("**Original column: same as English throughout.** The ported original, Paddleboard, has no")
[void]$out.AppendLine("repository and no separate source-language field anywhere in this repository (see")
[void]$out.AppendLine("ATTRIBUTION.md); its own text was already English. English is the original for every row.")
[void]$out.AppendLine()
[void]$out.AppendLine("Generated $(Get-Date -Format 'yyyy-MM-dd'), revision: working tree at the 2026-09-30 gender-agreement rule.")
[void]$out.AppendLine()

foreach ($ff in $frenchFiles) {
    $rel = $ff.FullName.Substring($frenchRoot.Length + 1) -replace '\\', '/'
    $frEntries = Get-Entries $ff.FullName
    if ($frEntries.Count -eq 0) { continue }

    $enPath = Join-Path $englishRoot $rel
    $enEntries = Get-Entries $enPath

    $hasNote = @{}
    $noteText = @{}
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        if ($fr -match '\?\?\?|TODO') {
            $hasNote[$key] = $true
            $noteText[$key] = 'Placeholder text left in the shipped string.'
        }
        elseif ($rel -match 'TraitDef' -and $key -match '\.label$') {
            $hasNote[$key] = $true
            $noteText[$key] = 'No gender switch: this is a plain trait label, not a `{PAWN_gender ? ...}` templated string, and English has no `labelFemale` either. Unsure whether the 2026-09-30 rule expects a middle-dot form here or leaves invariant trait labels alone.'
        }
    }
    $anyNote = $hasNote.Count -gt 0

    [void]$out.AppendLine("## $rel")
    [void]$out.AppendLine()
    if ($anyNote) {
        [void]$out.AppendLine("| Key or path | Original | English | French | ? |")
        [void]$out.AppendLine("|---|---|---|---|---|")
    } else {
        [void]$out.AppendLine("| Key or path | Original | English | French |")
        [void]$out.AppendLine("|---|---|---|---|")
    }
    foreach ($key in $frEntries.Keys) {
        $fr = $frEntries[$key]
        $en = $null
        if ($enEntries.Contains($key)) { $en = $enEntries[$key] }
        $orig = Resolve-DefField $defsRoot $key
        if ($null -eq $orig) { $orig = $en }   # Original = English throughout (see header note)
        if ($null -eq $en) { $en = $orig }     # a Def-only field with no Keyed English row
        if ($null -eq $orig) { $orig = '*(not found -- check by hand)*' }
        if ($null -eq $en) { $en = '*(not found -- check by hand)*' }
        $origCell = ($orig -replace '\|', '\|') -replace "`n", ' '
        $enCell = ($en -replace '\|', '\|') -replace "`n", ' '
        $frCell = ($fr -replace '\|', '\|') -replace "`n", ' '
        $keyCell = $key -replace '\|', '\|'
        if ($anyNote) {
            $note = if ($hasNote.ContainsKey($key)) { $noteText[$key] } else { '' }
            [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell | $note |")
        } else {
            [void]$out.AppendLine("| $keyCell | $origCell | $enCell | $frCell |")
        }
    }
    [void]$out.AppendLine()
}

[System.IO.File]::WriteAllText($OutFile, $out.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $OutFile"
